"""create card variants table

Revision ID: 0eac98a8accb
Revises: 64e710e11ea7
Create Date: 2026-08-04 15:50:47.581294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eac98a8accb'
down_revision: Union[str, Sequence[str], None] = '64e710e11ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_card_id', sa.Integer(), nullable=False),
    sa.Column('variant_key', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['catalog_card_id'], ['catalog_cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_card_id', 'variant_key', name='uq_card_variants_catalog_card_id_variant_key')
    )
    with op.batch_alter_table('card_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_variants_catalog_card_id'), ['catalog_card_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_variants_catalog_card_id'))

    op.drop_table('card_variants')
    # ### end Alembic commands ###
