"""create catalog cards table

Revision ID: 64e710e11ea7
Revises: d5ee3bb4be7f
Create Date: 2026-08-03 16:12:55.597031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e710e11ea7'
down_revision: Union[str, Sequence[str], None] = 'd5ee3bb4be7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_card_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('set_id', sa.String(length=100), nullable=False),
    sa.Column('set_name', sa.String(length=100), nullable=False),
    sa.Column('card_number', sa.String(length=50), nullable=False),
    sa.Column('rarity', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('reference_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reference_price_condition', sa.String(length=50), nullable=True),
    sa.Column('reference_price_variant', sa.String(length=50), nullable=True),
    sa.Column('reference_price_source', sa.String(length=50), nullable=True),
    sa.Column('reference_price_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_card_id', name='uq_catalog_cards_provider_card_id')
    )
    with op.batch_alter_table('catalog_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_cards_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_cards_name'))

    op.drop_table('catalog_cards')
    # ### end Alembic commands ###
