"""add collection item ownership

Revision ID: 7500aa297ad8
Revises: a06d67f6c679
Create Date: 2026-09-18 16:19:19.223571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7500aa297ad8'
down_revision: Union[str, Sequence[str], None] = 'a06d67f6c679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_items', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_collection_items_user_id'), 'collection_items', ['user_id'], unique=False)
    op.create_foreign_key(None, 'collection_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collection_items', type_='foreignkey')
    op.drop_index(op.f('ix_collection_items_user_id'), table_name='collection_items')
    op.drop_column('collection_items', 'user_id')
    # ### end Alembic commands ###
