"""add market pricing to card variants

Revision ID: 7f64a6890b0e
Revises: b947a39991a6
Create Date: 2026-08-16 14:30:24.317874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f64a6890b0e'
down_revision: Union[str, Sequence[str], None] = 'b947a39991a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('market_price_source', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('market_price_updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_variants', schema=None) as batch_op:
        batch_op.drop_column('currency')
        batch_op.drop_column('market_price_updated_at')
        batch_op.drop_column('market_price_source')
        batch_op.drop_column('market_price')

    # ### end Alembic commands ###
