"""create price snapshots table

Revision ID: 959d95fa90be
Revises: 7f64a6890b0e
Create Date: 2026-08-17 15:50:24.845068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '959d95fa90be'
down_revision: Union[str, Sequence[str], None] = '7f64a6890b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_variant_id', sa.Integer(), nullable=False),
    sa.Column('market_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('market_price >= 0', name='ck_price_snapshots_market_price_nonnegative'),
    sa.ForeignKeyConstraint(['card_variant_id'], ['card_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_price_snapshots_card_variant_id_observed_at', ['card_variant_id', 'observed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_price_snapshots_card_variant_id_observed_at')

    op.drop_table('price_snapshots')
    # ### end Alembic commands ###
