"""create collection items table

Revision ID: b947a39991a6
Revises: 0eac98a8accb
Create Date: 2026-08-05 15:58:41.832892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b947a39991a6'
down_revision: Union[str, Sequence[str], None] = '0eac98a8accb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_variant_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_price_per_card', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchase_currency', sa.String(length=3), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("condition IN ('near_mint', 'lightly_played', 'moderately_played', 'heavily_played', 'damaged', 'unknown')", name='ck_collection_items_condition_allowed'),
    sa.CheckConstraint('purchase_price_per_card >= 0', name='ck_collection_items_purchase_price_nonnegative'),
    sa.CheckConstraint('quantity > 0', name='ck_collection_items_quantity_positive'),
    sa.ForeignKeyConstraint(['card_variant_id'], ['card_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_items_card_variant_id'), ['card_variant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_items_card_variant_id'))

    op.drop_table('collection_items')
    # ### end Alembic commands ###
