"""add variant display name

Revision ID: c1544ded4c34
Revises: 959d95fa90be
Create Date: 2026-09-10 16:13:07.312482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1544ded4c34'
down_revision: Union[str, Sequence[str], None] = '959d95fa90be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_variants', sa.Column('display_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_variants', 'display_name')
    # ### end Alembic commands ###
